[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.netlify.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-api.netlify.app/api"
  VITE_APP_NAME = "React Course Demo"
  VITE_ENABLE_ANALYTICS = "true"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-backend-api-preview.netlify.app/api"
  VITE_APP_NAME = "React Course Demo (Preview)"
  VITE_ENABLE_ANALYTICS = "false"
